Traceback (most recent call last):
  File "c:\Users\S-FAMILY\Desktop\run\SAZOM.py", line 6, in <module>
    from rembg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\bg.py", line 6, in <module>
    import onnxruntime as ort
PS C:\Users\S-FAMILY> & C:/Users/S-FAMILY/AppData/Local/Programs/Python/Python39-32/python.exe c:/Users/S-FAMILY/Desktop/run/SAZOM.py
Traceback (most recent call last):
  File "c:\Users\S-FAMILY\Desktop\run\SAZOM.py", line 6, in <module>
    from rembg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\bg.py", line 6, in <module>
    import onnxruntime as ort
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: %1 is not a valid Win32 application.
